run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - revive
    - gofumpt
    - goimports
    - unused
    - staticcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/Axel791/metricsalert

